# Generated by Django 4.1.2 on 2022-11-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bonous',
            new_name='bonus',
        ),
    ]
